
FROM node:20

RUN apt-get update && apt-get install -y iputils-ping nano net-tools && apt-get clean

WORKDIR /code

RUN deluser --remove-home node

RUN mkdir -p ./src/db/seeds

ENTRYPOINT ["sh", "-c", "npm install --no-audit && npm run dev:server"]
